version: "3"
services:
  minio:
    image: minio/minio
    container_name: minio
    labels:
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
      - traefik.http.routers.minio-console.rule=Host(`console-minio.example.com`)
      - traefik.http.routers.minio-console.service=minio-console

      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio.rule=Host(`minio.example.com`)
      - traefik.http.routers.minio.service=minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_URL=https://minio.example.com
      - MINIO_BROWSER_REDIRECT_URL=https://console-minio.example.com
      - MINIO_PROMETHEUS_URL=https://prometheus.example.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server /data --console-address ":9001"
    restart: unless-stopped

networks:
  default:
    name: gateway
    external: true
