version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    labels:
    - traefik=false
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
        - 5432:5432
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  default:
    name: postgres
    external: false