version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    labels:
    - traefik=false
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    ports:
        - 3306:3306
    volumes:
      - /data/mysql/data:/var/lib/mysql
    restart: unless-stopped

networks:
  default:
    name: mysql
    external: false