version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:2.8
    labels:
    - "traefik.http.routers.api.service=api@internal"
    environment:
    -  DNSPOD_API_KEY=${DNSPOD_API_KEY}
    command: 
    - --configFile=/data/traefik.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik:/data
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:8080/ping || exit 1"]
      interval: 3s
      retries: 12
    restart: unless-stopped
    
networks:
  default:
    name: gateway
    external: true
