version: "2"
services:
  mc-server:
    image: "itzg/minecraft-server:java11-jdk"
    container_name: mc-server
    labels:
    - traefik=false
    mem_limit: 10G
    cpus: 4
    ports:
      - 25565:25565
    environment:
      JVM_OPTS: "-XX:PermSize=1024m"
      MEMORY: "8G"
      TYPE: "CUSTOM"
      EULA: "TRUE"
      CUSTOM_SERVER: "forge.jar"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/mc-server:/data