version: "3"
services:
  qb:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    labels:
      - traefik.http.services.qb.loadbalancer.server.port=10000
    environment:
      - PUID=1000
      - PGID=100
      - WEBUI_PORT=10000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/qbittorrent/config:/config
      - /data/qbittorrent/webui:/webui
      - /mnt/hdd/pt:/downloads
    network_mode: "host"

    restart: unless-stopped