version: "3"
services:
  drone:
    image: drone/drone
    container_name: drone
    environment:
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_GITEA_SERVER=${gitea_server}
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=https
    volumes:
      - /data/drone/data:/data
    restart: unless-stopped
  drone-runner:
    image: drone/drone-runner-docker
    container_name: drone-runner
    environment:
      - DRONE_RPC_PROTO=http 
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=4 
      - DRONE_RUNNER_NAME=docker-runner
      - DRONE_UI_USERNAME=root
      - DRONE_UI_PASSWORD=root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    
networks:
  default:
    name: gateway
    external: true
    